import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {NavMenu} from "@/components/NavMenu";
import {AuthProvider} from "@/context/AuthContext";
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <AuthProvider>
        <NavMenu/>
        <main className="container flex min-h-screen max-w-5xl flex-col items-center justify-between py-32 px-16">
        {children}
        </main>
          <Toaster />
      </AuthProvider>
      </body>

    </html>
  );
}
